default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
development:
  <<: *default
  host: <%= ENV['PSDB_HOST_NAME'] %>
  database: <%= ENV['PSDB_DB_NAME'] %>
  username: <%= ENV['PSDB_USER'] %>
  password: <%= ENV['PSDB_USER_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['PSDB_DB_NAME'] %>_test

production:
  <<: *default
  host: <%= ENV['PSDB_HOST_NAME'] %>
  database: <%= ENV['PSDB_DB_NAME'] %>
  username: <%= ENV['PSDB_USER'] %>
  password: <%= ENV['PSDB_USER_PASSWORD'] %>
